spring:
  config:
    import: env.properties
  profiles:
    active: dev
  application:
    name: onlineStoreApi
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#   hibernate:
#     naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
#     naming:
#       implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#       physical-strategy: com.example.onlineStoreApi.core.utils.UpperCaseNamingStrategy

logging:
  file:
    path: logs
  level:
    root: ERROR
    com.example.onlineStoreApi: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


server:
  error:
    include-message: always