#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
#    username: aymanabdulrahman
#    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#       ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: ture
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#
#
#
